<?php
/** @package Sistemaigcar::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ClientePfMap.php");

/**
 * ClientePfDAO provides object-oriented access to the cliente_pf table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistemaigcar::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ClientePfDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $RazaoSocial;

	/** @var string */
	public $Email;

	/** @var int */
	public $Telefone;

	/** @var int */
	public $Celular;

	/** @var int */
	public $Cnpj;

	/** @var string */
	public $Endereco;

	/** @var string */
	public $Bairro;

	/** @var string */
	public $Cep;

	/** @var string */
	public $Cidade;

	/** @var string */
	public $EstadoUf;



}
?>